name: Hello World CI

on:
  push:
    branches: [ main ]

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Ejecutar Hello World
      run: python hello.py
